# Generated by Django 5.1.4 on 2025-01-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_hand', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('org_description', models.TextField()),
                ('org_logo', models.ImageField(default='areis-1.png', upload_to='org_logos')),
                ('org_profile_pic', models.ImageField(default='areis-2.jpg', upload_to='clan_profile')),
                ('org_website', models.URLField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('primary_game', models.CharField(blank=True, max_length=255, null=True)),
                ('other_games', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(max_length=50)),
                ('social_links', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
