# Generated by Django 5.1.4 on 2025-01-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Clan', 'verbose_name_plural': 'Clans'},
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_profile_pic',
            field=models.ImageField(default='areis-2.jpg', upload_to='org_profile'),
        ),
    ]
