# Generated by Django 5.1.4 on 2025-01-08 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('achievements', models.TextField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('games_played', models.IntegerField(default=0)),
                ('win_rate', models.FloatField(default=0.0)),
                ('total_wins', models.IntegerField(default=0)),
                ('total_losses', models.IntegerField(default=0)),
                ('social_links', models.JSONField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='static/images/profile_pics/')),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClanMembers', to='clubs.clans')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ClanMembers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
