# Generated by Django 5.1.4 on 2025-01-27 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_links', models.JSONField(blank=True, null=True)),
                ('profile_picture', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('role', models.CharField(blank=True, choices=[('admin', 'Admin'), ('captain', 'Captain'), ('member', 'Member')], max_length=100, null=True)),
                ('clan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='clubs.clans')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievements', models.JSONField(blank=True, null=True)),
                ('rank', models.CharField(blank=True, choices=[('rookie', 'Rookie'), ('prodigy', 'Prodigy'), ('veteran', 'Veteran'), ('legend', 'Legend'), ('superstar', 'Superstar'), ('elite', 'Elite'), ('mvp', 'MVP'), ('world_class', 'World-Class')], editable=False, max_length=20, null=True)),
                ('games_played', models.IntegerField(default=0)),
                ('win_rate', models.FloatField(default=0.0)),
                ('total_wins', models.IntegerField(default=0)),
                ('total_losses', models.IntegerField(default=0)),
                ('total_draws', models.IntegerField(default=0)),
                ('gd', models.IntegerField(default=0)),
                ('gf', models.IntegerField(default=0)),
                ('ga', models.IntegerField(default=0)),
                ('elo_rating', models.FloatField(default=1200, editable=False)),
                ('season', models.CharField(default='2025', max_length=20)),
                ('match_data', models.JSONField(blank=True, default=dict, null=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='users.profile')),
            ],
        ),
    ]
