# Generated by Django 5.1.4 on 2025-08-11 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerstats',
            old_name='games_played',
            new_name='total_matches',
        ),
    ]
