# Generated by Django 5.1.4 on 2025-08-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_games_played_playerstats_total_matches'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallink',
            options={'ordering': ['display_order', 'link_type']},
        ),
        migrations.AddField(
            model_name='sociallink',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which this link should appear'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='link_type',
            field=models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('website', 'Website'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='sociallink',
            unique_together={('profile', 'link_type')},
        ),
    ]
