# Generated by Django 5.1.4 on 2025-02-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_is_organizer_alter_profile_clan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstats',
            name='rank',
            field=models.CharField(choices=[('rookie', 'Rookie'), ('prodigy', 'Prodigy'), ('veteran', 'Veteran'), ('legend', 'Legend'), ('superstar', 'Superstar'), ('elite', 'Elite'), ('mvp', 'MVP'), ('world_class', 'World-Class')], default='Unranked', editable=False, max_length=20, null=True),
        ),
    ]
