# Generated by Django 5.1.4 on 2025-03-30 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_clans_leader_clans_members'),
        ('users', '0003_alter_playerstats_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='clan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clan_profiles', to='clubs.clans'),
        ),
    ]
