# Generated by Django 5.1.4 on 2025-01-10 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_alter_clans_clan_logo'),
        ('users', '0004_alter_profile_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='games_played',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_losses',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_wins',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='win_rate',
        ),
        migrations.AlterField(
            model_name='profile',
            name='clan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='clubs.clans'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('captain', 'Captain'), ('member', 'Member')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievements', models.JSONField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('games_played', models.IntegerField(default=0)),
                ('win_rate', models.FloatField(default=0.0)),
                ('total_wins', models.IntegerField(default=0)),
                ('total_losses', models.IntegerField(default=0)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='users.profile')),
            ],
        ),
    ]
