# Generated by Django 5.1.4 on 2025-03-30 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_remove_clans_leader_remove_clans_members'),
        ('users', '0004_alter_profile_clan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='clan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='clubs.clans'),
        ),
    ]
