# Generated by Django 5.1.4 on 2025-08-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_sociallink_link_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='static/images/default.jpg', upload_to='profile_pics'),
        ),
    ]
