# Generated by Django 5.1.4 on 2025-07-28 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_is_verified_profile_verification_sent_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='verification_sent_at',
        ),
    ]
