# Generated by Django 5.1.4 on 2025-01-10 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_alter_clans_clan_logo'),
        ('users', '0005_remove_profile_achievements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='clan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clan', to='clubs.clans'),
        ),
    ]
