# Generated by Django 5.1.4 on 2025-01-10 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_clan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='clan',
        ),
    ]
