# Generated by Django 5.1.4 on 2025-08-22 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallink',
            options={},
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='is_active',
        ),
    ]
