# Generated by Django 5.1.4 on 2025-09-20 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clans", "0009_remove_clans_created_by_remove_clans_groups_and_more"),
        ("users", "0007_alter_sociallink_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="clan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="clans.clan",
            ),
        ),
    ]
