# Generated by Django 5.1.4 on 2025-01-12 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_remove_clans_clan_members_remove_clans_clan_teams'),
        ('users', '0012_alter_profile_clan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstats',
            name='rank',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='clan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='clubs.clans'),
        ),
    ]
