# Generated by Django 5.1.4 on 2025-01-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_playerstats_rank_alter_profile_clan'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='total_draws',
            field=models.IntegerField(default=0),
        ),
    ]
