# Generated by Django 5.1.4 on 2025-01-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_playerstats_total_draws'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='ga',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='gd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='gf',
            field=models.IntegerField(default=0),
        ),
    ]
