# Generated by Django 5.1.4 on 2025-01-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_playerstats_elo_rating_playerstats_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstats',
            name='rank',
            field=models.CharField(blank=True, choices=[('rookie', 'Rookie'), ('prodigy', 'Prodigy'), ('veteran', 'Veteran'), ('legend', 'Legend'), ('superstar', 'Superstar'), ('elite', 'Elite'), ('mvp', 'MVP'), ('world_class', 'World-Class')], editable=False, max_length=20, null=True),
        ),
    ]
