# Generated by Django 5.1.4 on 2025-01-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_playerstats_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='match_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
