# Generated by Django 5.1.4 on 2025-08-07 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_object_id', models.PositiveIntegerField()),
                ('followed_object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('blocked', 'Blocked')], default='accepted', max_length=10)),
                ('is_mutual', models.BooleanField(default=False)),
                ('notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followed_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_type', to='contenttypes.contenttype')),
                ('follower_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_type', to='contenttypes.contenttype')),
            ],
            options={
                'unique_together': {('follower_content_type', 'follower_object_id', 'followed_content_type', 'followed_object_id')},
            },
        ),
    ]
