# Generated by Django 5.1.4 on 2025-06-26 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_id', models.PositiveIntegerField()),
                ('followed_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_type', to='contenttypes.contenttype')),
                ('follower_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_type', to='contenttypes.contenttype')),
            ],
            options={
                'unique_together': {('follower_type', 'follower_id', 'followed_type', 'followed_id')},
            },
        ),
    ]
