# Generated by Django 5.1.4 on 2025-08-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower_type', 'follower_id'], name='Home_follow_followe_97983c_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['followed_type', 'followed_id'], name='Home_follow_followe_535c88_idx'),
        ),
    ]
