# Generated by Django 5.1.4 on 2024-12-30 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_member_joined_date_member_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
