# Generated by Django 5.1.4 on 2025-08-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clans',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this clan belongs to.', related_name='clan_set', related_query_name='clan', to='auth.group'),
        ),
        migrations.AddField(
            model_name='clans',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clans',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clans',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='clans',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='clans',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this clan.', related_name='clan_permissions_set', related_query_name='clan', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='clans',
            name='clan_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='clans',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
