# Generated by Django 5.1.4 on 2025-08-11 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clanstats',
            old_name='ranking',
            new_name='rank',
        ),
        migrations.RenameField(
            model_name='clanstats',
            old_name='draws',
            new_name='total_draws',
        ),
        migrations.RenameField(
            model_name='clanstats',
            old_name='losses',
            new_name='total_losses',
        ),
        migrations.RenameField(
            model_name='clanstats',
            old_name='wins',
            new_name='total_wins',
        ),
    ]
