# Generated by Django 5.1.4 on 2025-08-13 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0002_rename_ranking_clanstats_rank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clans',
            name='social_links',
        ),
        migrations.CreateModel(
            name='ClanSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('website', 'Website'), ('other', 'Other')], max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which this link should appear')),
                ('is_active', models.BooleanField(default=True)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='clans.clans')),
            ],
            options={
                'ordering': ['display_order', 'link_type'],
                'unique_together': {('clan', 'link_type')},
            },
        ),
    ]
