# Generated by Django 5.1.4 on 2025-08-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0002_clans_groups_clans_is_active_clans_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clans',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clans',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
