# Generated by Django 5.1.4 on 2025-08-15 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0003_remove_clans_social_links_clansociallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clansociallink',
            name='link_type',
            field=models.CharField(choices=[('discord', 'Discord'), ('whatsapp', 'WhatsApp'), ('x', 'X / Twitter'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('twitch', 'Twitch'), ('website', 'Website'), ('other', 'Other')], max_length=20),
        ),
    ]
