# Generated by Django 5.1.4 on 2025-08-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0004_alter_clansociallink_link_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clansociallink',
            name='link_type',
            field=models.CharField(choices=[('x', 'X / Twitter'), ('whatsapp', 'WhatsApp'), ('discord', 'Discord'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('twitch', 'Twitch'), ('website', 'Website'), ('other', 'Other')], max_length=20),
        ),
    ]
