# Generated by Django 5.1.4 on 2025-08-22 00:31

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0005_alter_clansociallink_link_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clans',
            name='phone',
        ),
        migrations.AlterField(
            model_name='clans',
            name='clan_tag',
            field=models.CharField(help_text='Clan tag must be unique and up to 4 characters long.', max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='clans',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
