# Generated by Django 5.1.4 on 2025-08-22 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0006_remove_clans_phone_alter_clans_clan_tag_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clansociallink',
            options={},
        ),
        migrations.RemoveField(
            model_name='clansociallink',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='clansociallink',
            name='is_active',
        ),
    ]
