# Generated by Django 5.1.4 on 2025-09-20 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clans", "0007_alter_clansociallink_options_and_more"),
    ]

    operations = []
