# Generated by Django 5.1.4 on 2025-09-20 02:33

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("clans", "0008_auto_20250919_2128"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clans",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="clans",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="clans",
            name="user_permissions",
        ),
        migrations.AlterModelOptions(
            name="clanjoinrequest",
            options={
                "verbose_name": "Clan Join Request",
                "verbose_name_plural": "Clan Join Requests",
            },
        ),
        migrations.AlterModelOptions(
            name="clansociallink",
            options={
                "verbose_name": "Clan Social Link",
                "verbose_name_plural": "Clan Social Links",
            },
        ),
        migrations.RenameField(
            model_name="clanjoinrequest",
            old_name="player",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="clanstats",
            old_name="player_conceeded",
            new_name="player_conceded",
        ),
        migrations.AddField(
            model_name="clanjoinrequest",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="clansociallink",
            name="link_type",
            field=models.CharField(
                choices=[
                    ("discord", "Discord"),
                    ("whatsapp", "WhatsApp"),
                    ("x", "X / Twitter"),
                    ("instagram", "Instagram"),
                    ("tiktok", "TikTok"),
                    ("youtube", "YouTube"),
                    ("twitch", "Twitch"),
                    ("website", "Website"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Clan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "tag",
                    models.CharField(
                        help_text="Clan tag must be unique and up to 6 characters long.",
                        max_length=6,
                        unique=True,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("description", models.TextField()),
                (
                    "logo",
                    models.ImageField(
                        default="clan-default.png", upload_to="clan_logos"
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        default="clan-profile-default.jpg", upload_to="clan_profiles"
                    ),
                ),
                ("website", models.URLField(blank=True, null=True)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                (
                    "primary_game",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "other_games",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("is_recruiting", models.BooleanField(default=False)),
                ("recruitment_requirements", models.TextField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this clan belongs to.",
                        related_name="clan_set",
                        related_query_name="clan",
                        to="auth.group",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this clan.",
                        related_name="clan_permissions_set",
                        related_query_name="clan",
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clan",
                "verbose_name_plural": "Clans",
            },
        ),
        migrations.AlterField(
            model_name="clanjoinrequest",
            name="clan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="clans.clan"
            ),
        ),
        migrations.AlterField(
            model_name="clansociallink",
            name="clan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_links",
                to="clans.clan",
            ),
        ),
        migrations.AlterField(
            model_name="clanstats",
            name="clan",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stats",
                to="clans.clan",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="clanjoinrequest",
            unique_together={("user", "clan")},
        ),
        migrations.CreateModel(
            name="ClanMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("leader", "Leader"),
                            ("captain", "Captain"),
                            ("member", "Member"),
                            ("recruit", "Recruit"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "clan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clan_members",
                        to="clans.clan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Clan Member",
                "verbose_name_plural": "Clan Members",
            },
        ),
    ]
