# Generated by Django 5.1.4 on 2025-09-20 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clans", "0009_remove_clans_created_by_remove_clans_groups_and_more"),
        ("tournaments", "0011_remove_clantournamentplayer_tournament_and_more"),
        ("users", "0008_alter_profile_clan"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Clans",
        ),
        migrations.AlterUniqueTogether(
            name="clanmember",
            unique_together={("clan", "user")},
        ),
    ]
