# Generated by Django 5.1.4 on 2025-01-27 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clan_name', models.CharField(max_length=255)),
                ('clan_tag', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('clan_description', models.TextField()),
                ('clan_logo', models.ImageField(default='areis-1.png', upload_to='clan_logos')),
                ('clan_profile_pic', models.ImageField(default='areis-2.jpg', upload_to='clan_profile')),
                ('clan_website', models.URLField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('primary_game', models.CharField(blank=True, max_length=255, null=True)),
                ('other_games', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(max_length=50)),
                ('social_links', models.JSONField(blank=True, null=True)),
                ('is_recruiting', models.BooleanField(default=False)),
                ('recruitment_requirements', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Clan',
                'verbose_name_plural': 'Clans',
            },
        ),
        migrations.CreateModel(
            name='ClanStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_matches', models.IntegerField(default=0, editable=False)),
                ('win_rate', models.FloatField(default=0.0, editable=False)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('ranking', models.CharField(blank=True, choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond'), ('master', 'Master'), ('grandmaster', 'Grandmaster'), ('champion', 'Champion'), ('invincible', 'Invincible')], editable=False, max_length=20, null=True)),
                ('gd', models.IntegerField(default=0)),
                ('gf', models.IntegerField(default=0)),
                ('ga', models.IntegerField(default=0)),
                ('average_team_score', models.FloatField(default=0.0, editable=False)),
                ('achievements', models.JSONField(blank=True, null=True)),
                ('elo_rating', models.FloatField(default=1200, editable=False)),
                ('match_data', models.JSONField(blank=True, default=dict, null=True)),
                ('clan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stat', to='clubs.clans')),
            ],
        ),
    ]
