# Generated by Django 5.1.4 on 2025-01-08 21:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clan_name', models.CharField(max_length=255)),
                ('clan_tag', models.CharField(max_length=10, unique=True)),
                ('clan_description', models.TextField()),
                ('clan_logo', models.ImageField(blank=True, null=True, upload_to='static/images/clan_logos/')),
                ('clan_website', models.URLField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('primary_game', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(max_length=50)),
                ('timezone', models.CharField(max_length=50)),
                ('clan_members', models.IntegerField(default=0)),
                ('active_members', models.IntegerField(default=0, editable=False)),
                ('clan_teams', models.IntegerField(default=0, editable=False)),
                ('games_played', models.IntegerField(default=0, editable=False)),
                ('total_matches', models.IntegerField(default=0, editable=False)),
                ('win_rate', models.FloatField(default=0.0, editable=False, help_text='Win percentage (e.g., 75.5 for 75.5%)')),
                ('ranking', models.IntegerField(blank=True, editable=False, null=True)),
                ('trophies', models.IntegerField(default=0, editable=False)),
                ('highest_trophy', models.IntegerField(default=0, editable=False)),
                ('average_team_score', models.FloatField(default=0.0, editable=False)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('discord_link', models.URLField(blank=True, null=True)),
                ('social_links', models.JSONField(blank=True, help_text='Store links to Twitter, Instagram, Twitch, etc.', null=True)),
                ('achievements', models.TextField(blank=True, null=True)),
                ('clan_theme', models.CharField(blank=True, max_length=100, null=True)),
                ('merchandise', models.BooleanField(default=False)),
                ('is_recruiting', models.BooleanField(default=False)),
                ('recruitment_requirements', models.TextField(blank=True, null=True)),
                ('application_link', models.URLField(blank=True, null=True)),
                ('clan_roles', models.TextField(blank=True, help_text='Define roles like Leader, Co-leader, Members, etc.', null=True)),
                ('teams_list', models.JSONField(blank=True, help_text='Store information about teams in JSON format', null=True)),
                ('sponsors', models.TextField(blank=True, null=True)),
                ('leaderboard_position', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Clan',
                'verbose_name_plural': 'Clans',
            },
        ),
    ]
