# Generated by Django 5.1.4 on 2025-01-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clans',
            name='active_members',
        ),
        migrations.RemoveField(
            model_name='clans',
            name='clan_roles',
        ),
        migrations.RemoveField(
            model_name='clans',
            name='clan_theme',
        ),
        migrations.RemoveField(
            model_name='clans',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='clans',
            name='discord_link',
        ),
        migrations.RemoveField(
            model_name='clans',
            name='games_played',
        ),
        migrations.RemoveField(
            model_name='clans',
            name='highest_trophy',
        ),
        migrations.RemoveField(
            model_name='clans',
            name='merchandise',
        ),
        migrations.RemoveField(
            model_name='clans',
            name='sponsors',
        ),
        migrations.RemoveField(
            model_name='clans',
            name='teams_list',
        ),
        migrations.RemoveField(
            model_name='clans',
            name='trophies',
        ),
        migrations.AddField(
            model_name='clans',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clans',
            name='other_games',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clans',
            name='achievements',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clans',
            name='clan_teams',
            field=models.TextField(default=0),
        ),
    ]
