# Generated by Django 5.1.4 on 2025-01-08 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_remove_clans_active_members_remove_clans_clan_roles_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clans',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clans',
            name='draws',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clans',
            name='wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clans',
            name='clan_members',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clans',
            name='social_links',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clans',
            name='win_rate',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
