# Generated by Django 5.1.4 on 2025-01-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_clans_created_by_clans_draws_clans_wins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clans',
            name='clan_tag',
            field=models.CharField(max_length=10),
        ),
    ]
