# Generated by Django 5.1.4 on 2025-01-31 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_clans_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanstats',
            name='player_conceeded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clanstats',
            name='player_scored',
            field=models.IntegerField(default=0),
        ),
    ]
