# Generated by Django 5.1.4 on 2025-01-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_alter_clans_clan_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clans',
            name='clan_logo',
            field=models.ImageField(upload_to='clan_logos'),
        ),
    ]
