# Generated by Django 5.1.4 on 2025-03-30 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_clanstats_player_conceeded_clanstats_player_scored'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clans',
            name='leader',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clan_leader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clans',
            name='members',
            field=models.ManyToManyField(related_name='clan_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
