# Generated by Django 5.1.4 on 2025-01-11 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_alter_clans_clan_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clans',
            name='clan_profile_pic',
            field=models.ImageField(default='areis-2.jpg', upload_to='clan_profile'),
        ),
        migrations.AlterField(
            model_name='clans',
            name='clan_logo',
            field=models.ImageField(default='areis-1.png', upload_to='clan_logos'),
        ),
    ]
