# Generated by Django 5.1.4 on 2025-03-30 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_clans_leader_clans_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clans',
            name='leader',
        ),
        migrations.RemoveField(
            model_name='clans',
            name='members',
        ),
    ]
