# Generated by Django 5.1.4 on 2025-01-12 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_clans_clan_profile_pic_alter_clans_clan_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clans',
            name='clan_members',
        ),
        migrations.RemoveField(
            model_name='clans',
            name='clan_teams',
        ),
    ]
