# Generated by Django 5.1.4 on 2025-01-12 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_remove_clans_clan_members_remove_clans_clan_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clans',
            name='timezone',
        ),
    ]
