# Generated by Django 5.1.4 on 2025-01-12 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_remove_clans_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clans',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='clans',
            name='application_link',
        ),
        migrations.RemoveField(
            model_name='clans',
            name='average_team_score',
        ),
        migrations.RemoveField(
            model_name='clans',
            name='draws',
        ),
        migrations.RemoveField(
            model_name='clans',
            name='leaderboard_position',
        ),
        migrations.RemoveField(
            model_name='clans',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='clans',
            name='ranking',
        ),
        migrations.RemoveField(
            model_name='clans',
            name='total_matches',
        ),
        migrations.RemoveField(
            model_name='clans',
            name='win_rate',
        ),
        migrations.RemoveField(
            model_name='clans',
            name='wins',
        ),
        migrations.CreateModel(
            name='ClanStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_matches', models.IntegerField(default=0, editable=False)),
                ('win_rate', models.FloatField(default=0.0, editable=False)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('ranking', models.IntegerField(blank=True, editable=False, null=True)),
                ('average_team_score', models.FloatField(default=0.0, editable=False)),
                ('achievements', models.JSONField(blank=True, null=True)),
                ('leaderboard_position', models.IntegerField(blank=True, null=True)),
                ('clan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='clubs.clans')),
            ],
        ),
    ]
