# Generated by Django 5.1.4 on 2025-01-12 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_remove_clans_achievements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanstats',
            name='clan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stat', to='clubs.clans'),
        ),
    ]
