# Generated by Django 5.1.4 on 2025-01-13 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_alter_clanstats_clan'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanstats',
            name='ga',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clanstats',
            name='gd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clanstats',
            name='gf',
            field=models.IntegerField(default=0),
        ),
    ]
