# Generated by Django 5.1.4 on 2025-01-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_clanstats_ga_clanstats_gd_clanstats_gf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clans',
            name='created_by',
        ),
        migrations.AddField(
            model_name='clans',
            name='email',
            field=models.EmailField(default='dwomohaustin14@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clans',
            name='password',
            field=models.CharField(default='dwomohaustin14@gmail.com', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clans',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
