# Generated by Django 5.1.4 on 2025-01-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0012_remove_clans_created_by_clans_email_clans_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clans',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
