# Generated by Django 5.1.4 on 2025-01-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0013_alter_clans_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanstats',
            name='elo_rating',
            field=models.FloatField(default=1200, editable=False),
        ),
        migrations.AddField(
            model_name='clanstats',
            name='season',
            field=models.CharField(default='2025', max_length=20),
        ),
    ]
