# Generated by Django 5.1.4 on 2025-01-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0014_clanstats_elo_rating_clanstats_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanstats',
            name='ranking',
            field=models.CharField(blank=True, choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond'), ('master', 'Master'), ('grandmaster', 'Grandmaster'), ('champion', 'Champion'), ('invincible', 'Invincible')], editable=False, max_length=20, null=True),
        ),
    ]
