# Generated by Django 5.1.4 on 2025-01-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0015_alter_clanstats_ranking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clanstats',
            name='leaderboard_position',
        ),
        migrations.RemoveField(
            model_name='clanstats',
            name='season',
        ),
        migrations.AddField(
            model_name='clanstats',
            name='match_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
