# Generated by Django 5.1.4 on 2025-08-07 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clans', '0001_initial'),
        ('users', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('player_mode', models.CharField(choices=[('fixed', 'Fixed'), ('dynamic', 'Dynamic')], default='dynamic', help_text='Whether clans can change players mid-tournament', max_length=10)),
                ('home_or_away', models.BooleanField(default=False, help_text='Select if this tournament is played home/away format.', verbose_name='Home or Away')),
                ('logo', models.ImageField(default='tours-defualt.jpg', upload_to='tour_logos')),
                ('tour_type', models.CharField(choices=[('league', 'League'), ('cup', 'Cup'), ('groups_knockout', 'Groups + Knockout')], max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('teams', models.ManyToManyField(related_name='clans', to='clans.clans')),
            ],
        ),
        migrations.CreateModel(
            name='IndiTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(default='tours-defualt.jpg', upload_to='tour_logos')),
                ('tour_type', models.CharField(choices=[('league', 'League'), ('cup', 'Cup'), ('groups_knockout', 'Groups + Knockout')], max_length=100)),
                ('home_or_away', models.BooleanField(default=False, help_text='Select if this tournament is played home/away format.', verbose_name='Home or Away')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(related_name='players', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ClanTournamentPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clans.clans')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.clantournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('clan', 'tournament', 'user')},
            },
        ),
    ]
