# Generated by Django 5.1.4 on 2025-07-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clantournament',
            name='home_or_away',
            field=models.BooleanField(default=False, help_text='Select if this tournament is played home/away format.', verbose_name='Home or Away'),
        ),
        migrations.AddField(
            model_name='inditournament',
            name='home_or_away',
            field=models.BooleanField(default=False, help_text='Select if this tournament is played home/away format.', verbose_name='Home or Away'),
        ),
        migrations.AlterField(
            model_name='clantournament',
            name='tour_type',
            field=models.CharField(choices=[('league', 'League'), ('cup', 'Cup'), ('groups_knockout', 'Groups + Knockout')], default='cup', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inditournament',
            name='tour_type',
            field=models.CharField(choices=[('league', 'League'), ('cup', 'Cup'), ('groups_knockout', 'Groups + Knockout')], default='cup', max_length=100),
            preserve_default=False,
        ),
    ]
