# Generated by Django 5.1.4 on 2025-08-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clantournament',
            name='logo',
            field=models.ImageField(default='static/images/tours-defualt.jpg', upload_to='tour_logos'),
        ),
        migrations.AlterField(
            model_name='inditournament',
            name='logo',
            field=models.ImageField(default='images/tours-defualt.jpg', upload_to='tour_logos'),
        ),
    ]
