# Generated by Django 5.1.4 on 2025-01-28 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('tournaments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField()),
                ('clan_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_clan_a', to='clubs.clans')),
                ('clan_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_clan_b', to='clubs.clans')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.clantournament')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wins', to='clubs.clans')),
            ],
        ),
        migrations.CreateModel(
            name='ClanMatchPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_a', models.IntegerField(default=0)),
                ('score_b', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_matches', to='tournaments.clanmatch')),
                ('player_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player_a', to='users.profile')),
                ('player_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player_b', to='users.profile')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wins_as_player', to='users.profile')),
            ],
        ),
    ]
