# Generated by Django 5.1.4 on 2025-08-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_alter_clantournament_logo_alter_inditournament_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clantournament',
            name='logo',
            field=models.ImageField(default='tours-defualt.jpg', upload_to='tour_logos'),
        ),
    ]
