# Generated by Django 5.1.4 on 2025-01-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_remove_clans_clan_members_remove_clans_clan_teams'),
        ('tournaments', '0002_rename_match_clanmatch_clantournament_and_more'),
        ('users', '0014_playerstats_total_draws'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clantournament',
            name='teams',
            field=models.ManyToManyField(related_name='ClanMatch', to='clubs.clans'),
        ),
        migrations.AlterField(
            model_name='inditournament',
            name='players',
            field=models.ManyToManyField(related_name='IndiMatch', to='users.profile'),
        ),
    ]
