# Generated by Django 5.1.4 on 2025-01-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_alter_clantournament_teams_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clantournament',
            name='logo',
            field=models.ImageField(default='tours-defualt.jpg', upload_to='tour_logos'),
        ),
        migrations.AddField(
            model_name='inditournament',
            name='logo',
            field=models.ImageField(default='tours-defualt.jpg', upload_to='tour_logos'),
        ),
    ]
