# Generated by Django 5.1.4 on 2025-08-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_alter_clantournament_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clantournament',
            name='created_by',
            field=models.TextField(blank=True, null=True),
        ),
    ]
