# Generated by Django 5.1.4 on 2025-01-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_clantournament_logo_inditournament_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanmatch',
            name='match_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
