# Generated by Django 5.1.4 on 2025-01-29 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_clanmatch_clanmatchplayer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clanmatchplayer',
            name='match',
        ),
        migrations.RemoveField(
            model_name='clanmatchplayer',
            name='player_a',
        ),
        migrations.RemoveField(
            model_name='clanmatchplayer',
            name='player_b',
        ),
        migrations.RemoveField(
            model_name='clanmatchplayer',
            name='winner',
        ),
        migrations.DeleteModel(
            name='ClanMatch',
        ),
        migrations.DeleteModel(
            name='ClanMatchPlayer',
        ),
    ]
