# Generated by Django 5.1.4 on 2025-01-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_clanmatch_match_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indimatch',
            name='player_1',
        ),
        migrations.RemoveField(
            model_name='indimatch',
            name='player_2',
        ),
        migrations.RemoveField(
            model_name='indimatch',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='indimatch',
            name='winner',
        ),
        migrations.AddField(
            model_name='clantournament',
            name='match_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inditournament',
            name='match_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ClanMatch',
        ),
        migrations.DeleteModel(
            name='IndiMatch',
        ),
    ]
