# Generated by Django 5.1.4 on 2025-08-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_alter_clantournament_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inditournament',
            name='created_by',
            field=models.TextField(blank=True, null=True),
        ),
    ]
