# Generated by Django 5.1.4 on 2025-01-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_remove_indimatch_player_1_remove_indimatch_player_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clantournament',
            name='type',
            field=models.CharField(blank=True, choices=[('league', 'League'), ('cup', 'Cup'), ('league_knockout', 'League + Knockout'), ('groups_knockout', 'Groups + Knockout')], max_length=100, null=True),
        ),
    ]
