# Generated by Django 5.1.4 on 2025-01-14 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_clantournament_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clantournament',
            old_name='type',
            new_name='tour_type',
        ),
    ]
