# Generated by Django 5.1.4 on 2025-08-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_alter_clantournament_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inditournament',
            name='logo',
            field=models.ImageField(default='tours-defualt.jpg', upload_to='tour_logos'),
        ),
    ]
