# Generated by Django 5.1.4 on 2025-01-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_rename_type_clantournament_tour_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clantournament',
            name='match_data',
        ),
        migrations.RemoveField(
            model_name='inditournament',
            name='match_data',
        ),
        migrations.AddField(
            model_name='inditournament',
            name='tour_type',
            field=models.CharField(blank=True, choices=[('league', 'League'), ('cup', 'Cup'), ('groups_knockout', 'Groups + Knockout')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clantournament',
            name='tour_type',
            field=models.CharField(blank=True, choices=[('league', 'League'), ('cup', 'Cup'), ('groups_knockout', 'Groups + Knockout')], max_length=100, null=True),
        ),
    ]
