# Generated by Django 5.1.4 on 2025-01-17 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_remove_clantournament_match_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clantournament',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='clantournament',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='inditournament',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='inditournament',
            name='start_date',
        ),
    ]
