# Generated by Django 5.1.4 on 2025-01-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0013_alter_clans_email'),
        ('tournaments', '0010_remove_clantournament_end_date_and_more'),
        ('users', '0015_playerstats_ga_playerstats_gd_playerstats_gf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clantournament',
            name='teams',
            field=models.ManyToManyField(related_name='clans', to='clubs.clans'),
        ),
        migrations.AlterField(
            model_name='inditournament',
            name='players',
            field=models.ManyToManyField(related_name='players', to='users.profile'),
        ),
    ]
