# Generated by Django 5.1.4 on 2025-09-20 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clans", "0009_remove_clans_created_by_remove_clans_groups_and_more"),
        ("organizations", "0002_initial"),
        ("tournaments", "0010_auto_20250919_2128"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clantournamentplayer",
            name="tournament",
        ),
        migrations.AlterUniqueTogether(
            name="clantournamentplayer",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="clantournamentplayer",
            name="clan",
        ),
        migrations.RemoveField(
            model_name="clantournamentplayer",
            name="user",
        ),
        migrations.RemoveField(
            model_name="inditournament",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="inditournament",
            name="players",
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "tournament_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual Tournament"),
                            ("clan", "Clan Tournament"),
                        ],
                        default="individual",
                        max_length=20,
                    ),
                ),
                (
                    "tour_format",
                    models.CharField(
                        choices=[
                            ("league", "League"),
                            ("cup", "Cup"),
                            ("groups_knockout", "Groups + Knockout"),
                        ],
                        default="league",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "max_participants",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "entry_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "prize_pool",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "home_or_away",
                    models.BooleanField(
                        default=False,
                        help_text="Select if this tournament is played home/away format.",
                        verbose_name="Home or Away",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        default="tours-default.jpg", upload_to="tour_logos"
                    ),
                ),
                ("match_data", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organized_tournaments",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tournament",
                "verbose_name_plural": "Tournaments",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="TournamentParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("eliminated", "Eliminated"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "clan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clans.clan",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="tournaments.tournament",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tournament Participant",
                "verbose_name_plural": "Tournament Participants",
                "unique_together": {("tournament", "clan"), ("tournament", "user")},
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.PositiveIntegerField()),
                ("home_score", models.PositiveIntegerField(blank=True, null=True)),
                ("away_score", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("is_knockout", models.BooleanField(default=False)),
                (
                    "knockout_stage",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="tournaments.tournament",
                    ),
                ),
                (
                    "away_participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_matches",
                        to="tournaments.tournamentparticipant",
                    ),
                ),
                (
                    "home_participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_matches",
                        to="tournaments.tournamentparticipant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Match",
                "verbose_name_plural": "Matches",
                "ordering": ["round_number", "scheduled_at"],
            },
        ),
        migrations.DeleteModel(
            name="ClanTournament",
        ),
        migrations.DeleteModel(
            name="ClanTournamentPlayer",
        ),
        migrations.DeleteModel(
            name="IndiTournament",
        ),
    ]
