name: Django CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python manage.py test

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd /var/www/aries/aries
            git fetch origin main
            git reset --hard origin/main
            /var/www/aries/server/bin/pip install -r requirements.txt
            /var/www/aries/server/bin/python manage.py migrate --noinput
            /var/www/aries/server/bin/python manage.py collectstatic --noinput
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx

      - name: Notify Discord on failure
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \":x: Django deploy failed on **${{ github.repository }}** \nBranch: **${{ github.ref_name }}** \nCommit: <${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}

      - name: Notify Discord on success
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \":white_check_mark: Django deploy succeeded on **${{ github.repository }}** \nBranch: **${{ github.ref_name }}** \nCommit: <${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}


        
        
